# Generated by Django 5.1.1 on 2024-09-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.category',),
        ),
        migrations.CreateModel(
            name='TertiaryCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Tertiary Category',
                'verbose_name_plural': 'Tertiary Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.category',),
        ),
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Top-Level Category',
                'verbose_name_plural': 'Top-Level Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.category',),
        ),
    ]
