# Generated by Django 5.1.1 on 2024-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_contact',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Это контакт'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_news',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Это новости'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Это персонал'),
        ),
    ]
