# Generated by Django 5.1.1 on 2024-09-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_is_contact_category_is_news_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '2. Подкатегория', 'verbose_name_plural': '2. Подкатегория'},
        ),
        migrations.AlterModelOptions(
            name='tertiarycategory',
            options={'verbose_name': '3. Третичная категория', 'verbose_name_plural': '3. Третичная категория'},
        ),
        migrations.AlterModelOptions(
            name='toplevelcategory',
            options={'verbose_name': '1. Основная категория', 'verbose_name_plural': '1. Основная категория'},
        ),
    ]
