# Generated by Django 5.1.1 on 2024-09-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_moderator',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пропуск модератора'),
        ),
    ]
