# Generated by Django 5.1.1 on 2024-09-19 05:23

import apps.news.validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(), apps.news.validation.validate_http_https], verbose_name='URL-адрес видео'),
        ),
        migrations.AddField(
            model_name='news',
            name='viewers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Зрители'),
        ),
    ]
