# Generated by Django 5.1.1 on 2024-09-20 07:12

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_video_url_news_viewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/staff', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_staff', to='news.postions', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудники университета',
                'verbose_name_plural': 'Сотрудники университета',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.postions')),
            ],
            options={
                'verbose_name': 'Должность Translation',
                'db_table': 'news_postions_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное имя')),
                ('work_date', models.CharField(blank=True, max_length=250, null=True, verbose_name='Рабочая дата')),
                ('private_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Личный телефон')),
                ('comapany_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Рабочий телефон')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Электронная почта')),
                ('work_activity', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Рабочая деятельность')),
                ('scientific_activity', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Научная деятельность')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.staffs')),
            ],
            options={
                'verbose_name': 'Сотрудники университета Translation',
                'db_table': 'news_staffs_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
