# Generated by Django 5.1.1 on 2024-09-20 07:22

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_postions_staffs_postionstranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Контактная информация института',
                'verbose_name_plural': 'Контактная информация института',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('comapany_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Рабочий телефон')),
                ('faks', models.CharField(blank=True, max_length=250, null=True, verbose_name='Факсы')),
                ('email', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Электронная почта')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.contactinfo')),
            ],
            options={
                'verbose_name': 'Контактная информация института Translation',
                'db_table': 'news_contactinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
