# Generated by Django 5.1.1 on 2024-09-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_contactinfo_contactinfotranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfotranslation',
            name='comapany_phone',
        ),
        migrations.RemoveField(
            model_name='contactinfotranslation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfotranslation',
            name='faks',
        ),
    ]
