# Generated by Django 5.1.1 on 2024-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_contactinfotranslation_comapany_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfotranslation',
            name='comapany_phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AddField(
            model_name='contactinfotranslation',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='contactinfotranslation',
            name='faks',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Факсы'),
        ),
    ]
