# Generated by Django 5.1.1 on 2024-09-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_is_contact_category_is_news_and_more'),
        ('news', '0009_contactinfotranslation_comapany_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id'], 'verbose_name': '5. Комментарий', 'verbose_name_plural': '5. Комментарий'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['id'], 'verbose_name': '3. Контактная информация института', 'verbose_name_plural': '3. Контактная информация института'},
        ),
        migrations.AlterModelOptions(
            name='contactinfotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '3. Контактная информация института Translation'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': '4. Новости', 'verbose_name_plural': '4. Новости'},
        ),
        migrations.AlterModelOptions(
            name='newstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '4. Новости Translation'},
        ),
        migrations.AlterModelOptions(
            name='postions',
            options={'ordering': ['id'], 'verbose_name': '1. Должность', 'verbose_name_plural': '1. Должность'},
        ),
        migrations.AlterModelOptions(
            name='postionstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '1. Должность Translation'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'ordering': ['id'], 'verbose_name': '2. Сотрудники университета', 'verbose_name_plural': '2. Сотрудники университета'},
        ),
        migrations.AlterModelOptions(
            name='staffstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '2. Сотрудники университета Translation'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_contact_info', to='menu.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_staff', to='menu.category', verbose_name='Категория'),
        ),
    ]
