# Generated by Django 5.1.1 on 2024-09-21 05:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_infoaboutinstitution_infoaboutinstitutiontranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoaboutinstitution',
            options={'ordering': ['id'], 'verbose_name': '6. Другая информация об институте', 'verbose_name_plural': '6. Другая информация об институте'},
        ),
        migrations.AlterModelOptions(
            name='infoaboutinstitutiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '6. Другая информация об институте Translation'},
        ),
        migrations.AlterField(
            model_name='infoaboutinstitutiontranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
