# Generated by Django 5.1.1 on 2024-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_infoaboutinstitution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='is_leadership',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Это лидерство'),
        ),
    ]
