# Generated by Django 5.1.1 on 2024-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinstitution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo', verbose_name='Логотип института'),
        ),
    ]
