# Generated by Django 5.1.1 on 2024-09-14 10:56

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0002_aboutinstitution_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMainPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('silder_image', models.ImageField(blank=True, null=True, upload_to='media/slider', verbose_name='Изб. слайдера')),
            ],
            options={
                'verbose_name': 'Основная часть слайдера',
                'verbose_name_plural': 'Основная часть слайдера',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SliderMainPartTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название слайдера')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main_part.slidermainpart')),
            ],
            options={
                'verbose_name': 'Основная часть слайдера Translation',
                'db_table': 'main_part_slidermainpart_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
