# Generated by Django 5.1.1 on 2024-09-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0003_slidermainpart_slidermainparttranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidermainpart',
            old_name='silder_image',
            new_name='slider_image',
        ),
    ]
