# Generated by Django 5.1.1 on 2024-09-14 11:18

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0005_partners_partnerstranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='URL-адрес видео для института')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='slidermainpart',
            options={'ordering': ['id'], 'verbose_name': 'Главная страница слайдера', 'verbose_name_plural': 'Главная страница слайдера'},
        ),
        migrations.AlterModelOptions(
            name='slidermainparttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Главная страница слайдера Translation'},
        ),
        migrations.CreateModel(
            name='VideoInstitutionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название видео')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main_part.videoinstitution')),
            ],
            options={
                'verbose_name': 'Видео Translation',
                'db_table': 'main_part_videoinstitution_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
