# Generated by Django 5.1.1 on 2024-10-09 10:45

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0006_videoinstitution_alter_slidermainpart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/announcement', verbose_name='Логотип')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': '5. Объявления',
                'verbose_name_plural': '5. Объявления',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='aboutinstitution',
            options={'ordering': ['id'], 'verbose_name': '1. Об институте', 'verbose_name_plural': '1. Об институте'},
        ),
        migrations.AlterModelOptions(
            name='aboutinstitutiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '1. Об институте Translation'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['id'], 'verbose_name': '3. Партнеры', 'verbose_name_plural': '3. Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='partnerstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '3. Партнеры Translation'},
        ),
        migrations.AlterModelOptions(
            name='slidermainpart',
            options={'ordering': ['id'], 'verbose_name': '2. Главная страница слайдера', 'verbose_name_plural': '2. Главная страница слайдера'},
        ),
        migrations.AlterModelOptions(
            name='slidermainparttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '2. Главная страница слайдера Translation'},
        ),
        migrations.AlterModelOptions(
            name='videoinstitution',
            options={'ordering': ['id'], 'verbose_name': '4. Видео', 'verbose_name_plural': '4. Видео'},
        ),
        migrations.AlterModelOptions(
            name='videoinstitutiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '4. Видео Translation'},
        ),
        migrations.CreateModel(
            name='AnnouncementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название объявления')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main_part.announcement')),
            ],
            options={
                'verbose_name': '5. Объявления Translation',
                'db_table': 'main_part_announcement_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
